import {
  Zap as Charizard,
  User as Chiki,
  Users as Family,
  Bike,
  Snowflake,
  Shield,
  Heart,
  Ghost,
  Swords,
  Cat,
  Dog,
  Shield as Spider,
  Bird,
  Cloud,
} from "lucide-react";
import { Model } from "../sections/ModelGrid";

export const models: Model[] = [
  {
    id: 1,
    name: "Black Charizard",
    icon: Charizard,
    description: "Dark version of the classic Pokémon",
    complexity: "Medium",
    modelPath: "/black_charizard.glb",
    scale: 4,
  },
  {
    id: 2,
    name: "Chiki Funko",
    icon: Chiki,
    description: "Custom Funko Pop character",
    complexity: "Medium",
    modelPath: "/chiki_funko.glb",
    scale: 3.5,
  },
  {
    id: 3,
    name: "Mom carrying dog",
    icon: Chiki,
    description: "Animated version of Chiki character",
    complexity: "High",
    modelPath: "/mama_chiki.glb",
    scale: 4,
  },
  {
    id: 4,
    name: "Family Set",
    icon: Family,
    description: "Group of Funko-style characters",
    complexity: "High",
    modelPath: "/family_funkos.glb",
    scale: 4,
  },
  {
    id: 5,
    name: "Scooter Monster",
    icon: Bike,
    description: "Whimsical bike creature",
    complexity: "Medium",
    modelPath: "/scooter_monster.glb",
    scale: 4,
  },
  {
    id: 6,
    name: "Snowboard Model",
    icon: Snowflake,
    description: "Winter sports equipment",
    complexity: "Low",
    modelPath: "/snowboard.glb",
    scale: 4,
  },
  {
    id: 7,
    name: "Alphonse Elric",
    icon: Shield,
    description: "Fullmetal Alchemist armored hero.",
    complexity: "High",
    modelPath: "/FMA_alphonse.glb",
    scale: 4,
  },
  {
    id: 8,
    name: "White Batman",
    icon: Shield,
    description: "The dark knight in a white suit.",
    complexity: "High",
    modelPath: "/white_batman.glb",
  },
  {
    id: 9,
    name: "Spiderman",
    icon: Spider,
    description: "Your friendly neighborhood Spiderman.",
    complexity: "High",
    modelPath: "/spiderman.glb",
    scale: 4,
  },
  {
    id: 10,
    name: "Funko Hanami",
    icon: Ghost,
    description: "Hanami from Jujutsu Kaisen as a Funko.",
    complexity: "Medium",
    modelPath: "/funko_hanami.glb",
    scale: 4,
  },
  {
    id: 11,
    name: "Jujutsu Hanami",
    icon: Ghost,
    description: "Hanami from Jujutsu Kaisen.",
    complexity: "High",
    modelPath: "/jujutsu_hanami.glb",
    scale: 4,
  },
  {
    id: 12,
    name: "Samoyed Luffy",
    icon: Dog,
    description: "Luffy as a Samoyed dog.",
    complexity: "Medium",
    modelPath: "/samoyed_luffy.glb",
    scale: 4,
  },
  {
    id: 13,
    name: "Horror Dragon",
    icon: Swords,
    description: "A terrifying dragon.",
    complexity: "High",
    modelPath: "/horror_dragon.glb",
    scale: 3,
  },
  {
    id: 14,
    name: "Half-Life",
    icon: Cloud,
    description: "A model from the Half-Life series.",
    complexity: "Medium",
    modelPath: "/halflife.glb",
    scale: 3,
  },
  {
    id: 15,
    name: "Funko",
    icon: Chiki,
    description: "A generic Funko model.",
    complexity: "Low",
    modelPath: "/funko.glb",
    scale: 3,
  },
];
